# Generated by Django 3.2.9 on 2021-12-01 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='')),
                ('fullName', models.TextField(max_length=200)),
                ('proffession', models.TextField(max_length=200)),
                ('telegram', models.TextField(max_length=1024)),
                ('instagram', models.TextField(max_length=1024)),
                ('facebook', models.TextField(max_length=1024)),
            ],
        ),
    ]
