# Generated by Django 3.2.9 on 2021-12-06 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pub', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ThingCounts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('students', models.BigIntegerField()),
                ('teachers', models.BigIntegerField()),
                ('rooms', models.BigIntegerField()),
            ],
            options={
                'verbose_name_plural': 'Hisoblari',
            },
        ),
        migrations.AlterModelOptions(
            name='employes',
            options={'verbose_name_plural': 'Ishchilar'},
        ),
        migrations.AlterField(
            model_name='employes',
            name='img',
            field=models.ImageField(upload_to='media/imgs/'),
        ),
    ]
