# Generated by Django 3.2.9 on 2021-12-06 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pub', '0002_auto_20211206_1615'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thingcounts',
            name='rooms',
            field=models.CharField(max_length=100000),
        ),
        migrations.AlterField(
            model_name='thingcounts',
            name='students',
            field=models.CharField(max_length=100000),
        ),
        migrations.AlterField(
            model_name='thingcounts',
            name='teachers',
            field=models.CharField(max_length=100000),
        ),
    ]
