# Generated by Django 3.2.9 on 2021-12-07 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pub', '0003_auto_20211206_1638'),
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imgs', models.ImageField(upload_to='media/newsimg')),
                ('title', models.CharField(max_length=1024)),
                ('description', models.TextField()),
            ],
            options={
                'verbose_name_plural': 'Yangiliklar',
            },
        ),
    ]
