# Generated by Django 3.2.9 on 2021-12-07 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pub', '0004_news'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=1024)),
                ('name', models.CharField(max_length=1024)),
                ('text', models.TextField()),
            ],
            options={
                'verbose_name_plural': 'Xabarlar',
            },
        ),
    ]
