# Generated by Django 3.2.9 on 2021-12-20 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pub', '0006_auto_20211213_1630'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=1024)),
                ('description', models.TextField()),
            ],
            options={
                'verbose_name_plural': 'Biz haqimizda',
            },
        ),
        migrations.AlterModelOptions(
            name='videomessagenews',
            options={'verbose_name_plural': 'Video Yangiliklar'},
        ),
    ]
